"""save: índices en las FKs por las que SE CONSULTA

Una auditoría de salud (no de corrección) encontró 12 FKs del schema sin índice. Se indexan SOLO
las tres por las que el código consulta de verdad, contadas sobre `src/`:

  canonical_product.taxonomy_node_id  10 sitios — listado por categoría del sitio + filtros del admin
  canonical_product.brand_id          13 sitios — listado y detalle por marca
  product_match.canonical_product_id   4 sitios — incluye el lookup puntual de `repositories.py:2683`
                                                  («todos los matches de ESTE canónico»)

Sin ellos cada página de categoría es un scan secuencial del catálogo entero. Hoy da igual (287
productos), no con los ~100k a los que apunta Save con cinco cadenas. `ix_canonical_product_market`
no salva: en una base de un solo mercado selecciona todo.

Las otras NUEVE FKs sin índice se dejan a propósito. Sus columnas no aparecen en ninguna consulta
—sólo importarían para la cascada de un DELETE, que acá es una operación de mantenimiento— y cada
índice se paga en cada INSERT. La ingesta es escritura pesada: indexar por si acaso frenaría
justamente lo que más se hace.

AVISO sobre la evidencia: esto se razonó por conteo de sitios de consulta y práctica estándar, NO
medido con `EXPLAIN ANALYZE` sobre datos reales — las tablas estaban vacías cuando se escribió.
Vale revalidarlo después de la primera ingesta. Se crean ahora porque sobre una tabla vacía es
instantáneo, y sobre una de 100k filas hace falta `CONCURRENTLY` y una ventana.

Revision ID: 1953d56fa0d5
Revises: c7a1f39d84b2
Create Date: 2026-08-04 20:30:36.351103
"""
from __future__ import annotations

from alembic import op


revision = '1953d56fa0d5'
down_revision = 'c7a1f39d84b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_canonical_product_brand', 'canonical_product', ['brand_id'], unique=False, schema='save')
    op.create_index('ix_canonical_product_taxonomy_node', 'canonical_product', ['taxonomy_node_id'], unique=False, schema='save')
    op.create_index('ix_product_match_canonical', 'product_match', ['canonical_product_id'], unique=False, schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_match_canonical', table_name='product_match', schema='save')
    op.drop_index('ix_canonical_product_taxonomy_node', table_name='canonical_product', schema='save')
    op.drop_index('ix_canonical_product_brand', table_name='canonical_product', schema='save')
    # ### end Alembic commands ###
