"""save: contador de queries en el snapshot de corrida

Revision ID: 23f1d5c67366
Revises: d9b8ab9bb88a
Create Date: 2026-07-20 01:05:18.431483
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '23f1d5c67366'
down_revision = 'd9b8ab9bb88a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orchestration_run_snapshot', sa.Column('queries_total', sa.Integer(), server_default='0', nullable=False), schema='save')
    op.add_column('orchestration_run_snapshot', sa.Column('queries_processed', sa.Integer(), server_default='0', nullable=False), schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orchestration_run_snapshot', 'queries_processed', schema='save')
    op.drop_column('orchestration_run_snapshot', 'queries_total', schema='save')
    # ### end Alembic commands ###
