"""save: correlacion corrida-match-canonico (F4)

Revision ID: 383f4c14de46
Revises: 986cfadeb758
Create Date: 2026-07-19 11:07:03.811591
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '383f4c14de46'
down_revision = '986cfadeb758'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_product', sa.Column('origin_run_id', sa.Text(), nullable=True), schema='save')
    op.create_index('ix_canonical_product_origin_run', 'canonical_product', ['origin_run_id'], unique=False, schema='save')
    op.add_column('product_match', sa.Column('run_id', sa.Text(), nullable=True), schema='save')
    op.create_index('ix_product_match_run_status', 'product_match', ['run_id', 'status'], unique=False, schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_match_run_status', table_name='product_match', schema='save')
    op.drop_column('product_match', 'run_id', schema='save')
    op.drop_index('ix_canonical_product_origin_run', table_name='canonical_product', schema='save')
    op.drop_column('canonical_product', 'origin_run_id', schema='save')
    # ### end Alembic commands ###
