"""insights normalization (merchant, budget, space, savings_goal, recurring_rule)

Revision ID: 4cb3e311c6a6
Revises: 994974fcfb58
Create Date: 2026-06-26 10:35:16.045492
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4cb3e311c6a6'
down_revision = '994974fcfb58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_merchant_user_name'),
    schema='insights'
    )
    op.create_table('space',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('budget',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_account_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('limit_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_account_id'], ['insights.account.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['insights.merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('recurring_rule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('counter_account_id', sa.UUID(), nullable=False),
    sa.Column('cadence', sa.Text(), nullable=False),
    sa.Column('next_run', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['insights.account.id'], ),
    sa.ForeignKeyConstraint(['counter_account_id'], ['insights.account.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['insights.merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('savings_goal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('target_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['insights.account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('space_account',
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['insights.account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['insights.space.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('space_id', 'account_id'),
    schema='insights'
    )
    op.create_table('budget_alert_threshold',
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('percent', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['insights.budget.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'percent'),
    schema='insights'
    )
    op.add_column('account', sa.Column('icon', sa.Text(), nullable=True), schema='insights')
    op.drop_index(op.f('ix_posting_account_currency'), table_name='posting', schema='insights')
    op.create_index('ix_posting_account', 'posting', ['account_id'], unique=False, schema='insights')
    op.drop_column('posting', 'currency', schema='insights')
    op.add_column('transaction', sa.Column('merchant_id', sa.UUID(), nullable=True), schema='insights')
    op.create_foreign_key('transaction_merchant_id_fkey', 'transaction', 'merchant', ['merchant_id'], ['id'], source_schema='insights', referent_schema='insights')
    op.drop_column('transaction', 'merchant_name', schema='insights')
    op.drop_column('transaction', 'merchant_logo_url', schema='insights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('merchant_logo_url', sa.TEXT(), autoincrement=False, nullable=True), schema='insights')
    op.add_column('transaction', sa.Column('merchant_name', sa.TEXT(), autoincrement=False, nullable=True), schema='insights')
    op.drop_constraint('transaction_merchant_id_fkey', 'transaction', schema='insights', type_='foreignkey')
    op.drop_column('transaction', 'merchant_id', schema='insights')
    op.add_column('posting', sa.Column('currency', sa.CHAR(length=3), autoincrement=False, nullable=False), schema='insights')
    op.drop_index('ix_posting_account', table_name='posting', schema='insights')
    op.create_index(op.f('ix_posting_account_currency'), 'posting', ['account_id', 'currency'], unique=False, schema='insights')
    op.drop_column('account', 'icon', schema='insights')
    op.drop_table('budget_alert_threshold', schema='insights')
    op.drop_table('space_account', schema='insights')
    op.drop_table('savings_goal', schema='insights')
    op.drop_table('recurring_rule', schema='insights')
    op.drop_table('budget', schema='insights')
    op.drop_table('space', schema='insights')
    op.drop_table('merchant', schema='insights')
    # ### end Alembic commands ###
