"""save: imagenes multiples y descripcion por tienda

Los adapters ya recibían TODAS las imágenes de cada tienda y las descartaban: VTEX manda un array
y usábamos `[0]`; Bravo manda `nimgArticulo` (cuántas hay) con URL indexada y construíamos sólo
`_1.png`. La descripción no se capturaba en ninguno.

Estas imágenes son las CANDIDATAS de la galería del canónico (1ª, 2ª, 3ª): sin ellas la galería
sólo puede ofrecer una foto por tienda.

Backfill: la `image_url` que ya tenía cada store_product pasa a ser su posición 1, para que las
candidatas no desaparezcan hasta que corra la próxima ingesta.

Revision ID: 6c5a4babce47
Revises: a5b790af00bb
Create Date: 2026-07-25 12:29:06.175007
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6c5a4babce47'
down_revision = 'a5b790af00bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_product_image',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_product_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_product_id'], ['save.store_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_product_id', 'position', name='uq_store_product_image_position'),
    schema='save'
    )
    op.create_index('ix_store_product_image_store_product', 'store_product_image', ['store_product_id'], unique=False, schema='save')
    op.add_column('store_product', sa.Column('description', sa.Text(), nullable=True), schema='save')

    # Backfill: la imagen que ya conocíamos pasa a ser la posición 1 de su tienda.
    op.execute(
        """
        INSERT INTO save.store_product_image (store_product_id, url, position)
        SELECT id, image_url, 1
          FROM save.store_product
         WHERE image_url IS NOT NULL AND image_url <> ''
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_product', 'description', schema='save')
    op.drop_index('ix_store_product_image_store_product', table_name='store_product_image', schema='save')
    op.drop_table('store_product_image', schema='save')
    # ### end Alembic commands ###
