"""save: PROCEDENCIA — qué query de la canasta descubrió cada store_product

Hasta ahora un `store_product` no sabía de qué búsqueda salió, y esa ausencia bloqueaba tres cosas:

1. **Medir el clasificador contra una etiqueta humana.** `basket_query.category_label` es un rubro
   CURADO; sin saber qué query trajo el producto no se puede cruzar contra la hoja que el
   clasificador le asignó, así que no había forma de estimar acierto sin etiquetar a mano.
2. **Saber qué queries son productivas.** Una que no devuelve nada gasta una request real contra la
   tienda en cada corrida, en silencio.
3. Un eventual portón de rubro en el clasificador — deliberadamente NO implementado todavía (ver
   abajo).

NULL cuando no hubo query detrás: el browse REST de Bravo itera SECCIONES y Loop B re-pide por
`external_id`. **No se inventa una.** Rellenarla con el nombre de una sección haría que la medición
del punto 1 compare contra algo que ningún humano curó.

SIN FK a `basket_query`: la query se puede borrar o renombrar desde la consola, y la procedencia
histórica del producto no debe morir con ella. Es un HECHO de la corrida, no una relación viva.

Se escribe SOLO en el alta, nunca en la re-observación: registra quién DESCUBRIÓ el producto, y eso
pasó una vez. Pisarlo en cada refresh lo convertiría en "la última query que lo volvió a ver".

POR QUÉ NO SE IMPLEMENTA (todavía) EL PORTÓN DE RUBRO EN EL CLASIFICADOR: a diferencia del portón de
departamento —que se ignora si el área queda sin candidatos—, un rubro EQUIVOCADO fuerza una hoja
incorrecta-pero-dentro-del-rubro por encima de una correcta-fuera. Puede EMPEORAR: no es aditivo. Y
la señal falta justo donde clasificar es más difícil (browse, Loop B, backfill). Esta columna es lo
que permite MEDIR primero cuánto se ganaría y cuál es la tasa de conflicto; el portón se gana con esa
evidencia, no con la intuición de que "ayudaría".

Revision ID: 90d9a530c197
Revises: 1953d56fa0d5
Create Date: 2026-08-04 21:47:26.448841
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '90d9a530c197'
down_revision = '1953d56fa0d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_product', sa.Column('source_query', sa.Text(), nullable=True), schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_product', 'source_query', schema='save')
    # ### end Alembic commands ###
