"""insights schema (ledger)

Revision ID: 994974fcfb58
Revises: df87365ab7ea
Create Date: 2026-06-26 10:00:42.034898
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '994974fcfb58'
down_revision = 'df87365ab7ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS insights")   # ADR 33: schema por contexto (autogenerate NO lo crea)
    op.create_table('account',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('counter_account_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('merchant_name', sa.Text(), nullable=True),
    sa.Column('merchant_logo_url', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('essential', sa.Boolean(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['insights.account.id'], ),
    sa.ForeignKeyConstraint(['counter_account_id'], ['insights.account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_transaction_idempotency_key'),
    schema='insights'
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['insights.transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    op.create_table('posting',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['insights.account.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['insights.journal_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='insights'
    )
    # índice del hot-path: balance(account) = Σ posting WHERE account_id (+ currency) · §12·B
    op.create_index(
        'ix_posting_account_currency', 'posting', ['account_id', 'currency'], schema='insights'
    )
    op.create_index(
        'ix_transaction_user_occurred', 'transaction', ['user_id', 'occurred_at'], schema='insights'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_user_occurred', table_name='transaction', schema='insights')
    op.drop_index('ix_posting_account_currency', table_name='posting', schema='insights')
    op.drop_table('posting', schema='insights')
    op.drop_table('journal_entry', schema='insights')
    op.drop_table('transaction', schema='insights')
    op.drop_table('account', schema='insights')
    op.execute("DROP SCHEMA IF EXISTS insights CASCADE")
    # ### end Alembic commands ###
