"""save: galeria ordenada de imagenes del canonico

Un canónico pasa de tener UNA imagen a tener una lista ORDENADA (1ra, 2da, 3ra…). Cada fila
recuerda de qué `store_product` salió, que es lo que permite decir "la 2da la tomamos de Sirena"
y volver a ella si la tienda la cambia.

**`canonical_product.image_url` NO se elimina**: pasa a ser el espejo denormalizado de la posición
1. El sitio público (og:image, canonical, tarjetas, rails) la lee de ahí, y romper ese contrato
por un cambio interno del admin sería cambiar el SEO sin querer. Quien escribe la galería mantiene
el espejo.

Backfill: cada canónico que ya tenía imagen arranca con esa misma URL en posición 1, para que la
galería no nazca vacía donde ya había un dato bueno.

Revision ID: a5b790af00bb
Revises: 1b48d0f4dc93
Create Date: 2026-07-25 12:11:46.991821
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a5b790af00bb'
down_revision = '1b48d0f4dc93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_product_image',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_product_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_store_product_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['save.canonical_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_store_product_id'], ['save.store_product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_product_id', 'position', name='uq_canonical_product_image_position'),
    schema='save'
    )
    op.create_index('ix_canonical_product_image_canonical', 'canonical_product_image', ['canonical_product_id'], unique=False, schema='save')

    # Backfill: la imagen actual del canónico pasa a ser su posición 1.
    op.execute(
        """
        INSERT INTO save.canonical_product_image (canonical_product_id, url, position)
        SELECT id, image_url, 1
          FROM save.canonical_product
         WHERE image_url IS NOT NULL AND image_url <> ''
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canonical_product_image_canonical', table_name='canonical_product_image', schema='save')
    op.drop_table('canonical_product_image', schema='save')
    # ### end Alembic commands ###
