"""save: grupos de productos del usuario

Revision ID: c7428f917fb3
Revises: 90d9a530c197
Create Date: 2026-08-24 21:38:45.502037
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c7428f917fb3'
down_revision = '90d9a530c197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_product_group_user_name'),
    schema='save'
    )
    op.create_index('ix_product_group_user', 'product_group', ['user_id'], unique=False, schema='save')
    op.create_table('product_group_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('canonical_product_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['save.canonical_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['save.product_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'canonical_product_id', name='uq_product_group_item'),
    schema='save'
    )
    op.create_index('ix_product_group_item_group', 'product_group_item', ['group_id'], unique=False, schema='save')
    op.create_index('ix_product_group_item_product', 'product_group_item', ['canonical_product_id'], unique=False, schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_group_item_product', table_name='product_group_item', schema='save')
    op.drop_index('ix_product_group_item_group', table_name='product_group_item', schema='save')
    op.drop_table('product_group_item', schema='save')
    op.drop_index('ix_product_group_user', table_name='product_group', schema='save')
    op.drop_table('product_group', schema='save')
    # ### end Alembic commands ###
