"""save: snapshot de metricas por corrida (F4)

Revision ID: d9b8ab9bb88a
Revises: 383f4c14de46
Create Date: 2026-07-19 11:17:17.549894
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd9b8ab9bb88a'
down_revision = '383f4c14de46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestration_run_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dagster_run_id', sa.Text(), nullable=False),
    sa.Column('market_id', sa.Text(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('flow_key', sa.Text(), nullable=True),
    sa.Column('seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('refreshed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unmatched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('matched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_linked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('queued_for_review', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['save.orchestration_policy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['save.provider.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dagster_run_id', name='uq_run_snapshot_dagster_run'),
    schema='save'
    )
    op.create_index('ix_run_snapshot_policy', 'orchestration_run_snapshot', ['policy_id'], unique=False, schema='save')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_snapshot_policy', table_name='orchestration_run_snapshot', schema='save')
    op.drop_table('orchestration_run_snapshot', schema='save')
    # ### end Alembic commands ###
