"""identity schema

Revision ID: df87365ab7ea
Revises: 
Create Date: 2026-06-26 08:09:45.226011
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'df87365ab7ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")   # ADR 33: schema por contexto
    op.create_table('capability',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='identity'
    )
    op.create_table('role',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='identity'
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), server_default='es-DO', nullable=False),
    sa.Column('plan', sa.Text(), server_default='free', nullable=False),
    sa.Column('home_market_id', sa.CHAR(length=2), nullable=False),
    sa.Column('current_market_id', sa.CHAR(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_table('auth_identity',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_auth_identity_provider_subject'),
    schema='identity'
    )
    op.create_table('capability_market',
    sa.Column('capability_key', sa.Text(), nullable=False),
    sa.Column('market_id', sa.CHAR(length=2), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['capability_key'], ['identity.capability.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capability_key', 'market_id'),
    schema='identity'
    )
    op.create_table('role_capability',
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.Column('capability_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['capability_key'], ['identity.capability.key'], ),
    sa.ForeignKeyConstraint(['role_key'], ['identity.role.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_key', 'capability_key'),
    schema='identity'
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['role_key'], ['identity.role.key'], ),
    sa.ForeignKeyConstraint(['user_id'], ['identity.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_key'),
    schema='identity'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role', schema='identity')
    op.drop_table('role_capability', schema='identity')
    op.drop_table('capability_market', schema='identity')
    op.drop_table('auth_identity', schema='identity')
    op.drop_table('user', schema='identity')
    op.drop_table('role', schema='identity')
    op.drop_table('capability', schema='identity')
    op.execute("DROP SCHEMA IF EXISTS identity CASCADE")
    # ### end Alembic commands ###
