"""Integration — la BD migrada debe coincidir con los modelos SQLAlchemy. DB.

`alembic check` es la red que detecta drift: un modelo que cambió sin su migración, o una migración
aplicada a mano que el modelo no refleja. Sólo sirve si está VERDE — y estuvo rojo de forma
permanente, por dos índices que Alembic no podía ver en el metadata:

    uq_brand_market_key        UNIQUE (market_id, translate(upper(btrim(name)), 'ÁÀÄÂ…','AAAA…'))
    ix_provider_market_active  (market_id) WHERE archived_at IS NULL

Uno por EXPRESIÓN (deduplica marcas ignorando acentos) y otro PARCIAL (providers vivos). Los crean
migraciones y el ORM no los usa para consultar, así que no estaban declarados — y el autogenerate,
al no encontrarlos en el modelo, proponía DROPEARLOS en cada corrida. La migración `efec6851fef7`
documenta que hubo que borrar esa propuesta A MANO para no tirar dos índices en uso.

Un chequeo que siempre falla no es un chequeo: el ruido tapa la señal y nadie distingue el falso
positivo del drift de verdad. Se declararon los dos índices en `__table_args__` y este test fija el
resultado, para que la red no se vuelva a romper en silencio.
"""
from __future__ import annotations

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

_API_ROOT = Path(__file__).resolve().parents[3]


def test_alembic_check_reports_no_drift(db_session) -> None:  # type: ignore[no-untyped-def]
    """Si esto falla: o falta generar una migración, o hay un índice/constraint que la BD tiene y
    el modelo no declara. NO 'arreglar' borrando lo que el autogenerate propone dropear sin mirar
    antes qué es — puede estar en uso."""
    from alembic import command

    config = Config(str(_API_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_API_ROOT / "migrations"))

    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - sólo en drift real
        pytest.fail(f"la BD migrada no coincide con los modelos:\n{exc}")
